Added: join-lines, bin-lib-name-conflicts

diff --git a/bin/bash_setup b/bin/bash_setup
--- a/bin/bash_setup
+++ b/bin/bash_setup
@@ -77,6 +77,7 @@ case "$action" in
     cmd_print=""
     cmd=""
     nl_printed=""
+    BIN_NAME="$(basename "$file")"
     IFS=$'\n'
     for line in $(cat $file)
     do
@@ -101,6 +102,23 @@ case "$action" in
       fi
 
     done
+
+    dir_functions="$(dirname "$file")/lib"
+    [[ ! -d "$dir_functions" ]] && exit 0 || :
+
+    while read FILE; do
+      FUNCTION_NAME="$(basename "$FILE" .sh)"
+      echo -e "=== ${Bold}${FUNCTION_NAME}${Color_Off}"
+      while IFS= read LINE; do
+        if [[ "$LINE" =~ ^"# ===" ]]; then
+          LINE=${LINE/'# ==='/''}
+          LINE=${LINE/'{{CMD}}'/"${Green}${BIN_NAME}${Color_Off}  ${FUNCTION_NAME} "}
+          LINE=${LINE/'{{BIN}}'/"${Green}${BIN_NAME}${Color_Off}"}
+          LINE=${LINE/'{{NAME}}'/"${FUNCTION_NAME}"}
+          echo -e "   $LINE"
+        fi
+      done < <(cat "$FILE")
+    done < <(find "$dir_functions" -type f -iname "*.sh" | sort )
     ;;
 
   "help"|"--help")
@@ -474,8 +492,7 @@ case "$action" in
     #     ./.git
     #     ./dir/file.git/
 
-    files="$1"
-    shift
+    files="$1"; shift
     cmd="$@"
 
     if [[ -z "$@" ]]
@@ -493,9 +510,10 @@ case "$action" in
       path="${dir}$(echo "$CHANGE" | cut -d' ' -f 3)"
       file="$(basename $path)"
 
+      [[ ! -f "$path" ]] && continue || :
       echo ""
       echo === $CHANGE === "$cmd"
-      eval $cmd || :
+      $cmd || { stat="$?"; echo -e "=== ${Red}Failed${Color_Off}: $stat"; }
     done < <(inotifywait --quiet --monitor --event close_write --exclude .git/ $files)
     ;;
 
@@ -861,6 +879,12 @@ case "$action" in
     ;;
 
   *)
+    func_file="$THIS_DIR/bin/lib/${action}.sh"
+    if [[ -s "$func_file" ]]; then
+      source "$func_file"
+      "$action" "$@"
+      exit 0
+    fi
     echo "Unknown option: $action" 1>&2
     exit 1
     ;;
