Added: files-must-be-equal

diff --git a/bin/bash_setup b/bin/bash_setup
--- a/bin/bash_setup
+++ b/bin/bash_setup
@@ -712,6 +712,23 @@ case "$action" in
     cp -i "$orig" "$target"
     ;;
 
+  files-must-be-equal)
+    # === __ must-be-same  NAME  "file1"  "file2"
+    NAME="$1"; shift
+    FILE1="$1"; shift
+    FILE2="$1"; shift
+    # if [[ -s "$FILE1" ]] && ! diff <(bash_setup trim-file "$FILE1") <(bash_setup trim-file "$FILE2"); then
+    if [[ -s "$FILE1" ]] && ! diff <(bash_setup trim-file "$FILE1") <(bash_setup trim-file "$FILE2"); then
+      echo -e "=== $NAME ${Red}Failed${Color_Off}:"
+      echo -e "${Bold}      === Actual: =====${Color_Off} $FILE2"
+      cat "$FILE2"
+      echo -e "${Bold}      === Expected: ===${Color_Off} $FILE1"
+      cat "$FILE1"
+      echo -e "${Bold}      =================${Color_Off}"
+      exit 1
+    fi
+    ;;
+
   dirs-are-equal)
     # === __   dirs-are-equal    dir1   dir2
     # === This is mainly used for specs/testing.
@@ -731,6 +748,8 @@ case "$action" in
     # === Compare each file:
     while read FILE1 FILE2; do
       if ! diff "$FILE1" "$FILE2"; then
+        echo "FILE1: $FILE1" 1>&2
+        echo "FILE2: $FILE2" 1>&2
         exit 1
       fi
     done < <(paste <(find "$dir1" -type f | sort) <(find "$dir2" -type f | sort))
@@ -767,7 +786,7 @@ case "$action" in
 
     echo "four"     > "$dir1/file4";
     echo "not four" > "$dir2/file4";
-    if $0 dirs-are-equal "$dir1" "$dir2" > $TEMP/output; then
+    if $0 dirs-are-equal "$dir1" "$dir2" &> $TEMP/output; then
       echo -e "!!! ${Red}Failed${Color_Off} same names, different content: file4 == file4"
       cat $TEMP/output 1>&2
       exit 1
